# Generated by Django 5.2.14 on 2026-05-29 12:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=80, verbose_name='Usuário')),
                ('acao', models.CharField(max_length=200, verbose_name='Ação')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('tabela_afetada', models.CharField(max_length=100, verbose_name='Tabela Afetada')),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditorias',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=2, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='MaterialTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('composicao_quimica', models.TextField(verbose_name='Composição Química')),
                ('cor_predominante', models.CharField(max_length=30, verbose_name='Cor Predominante')),
            ],
            options={
                'verbose_name': 'Tipo de Material',
                'verbose_name_plural': 'Tipos de Material',
            },
        ),
        migrations.CreateModel(
            name='StatusMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Status de Movimentação',
                'verbose_name_plural': 'Status de Movimentação',
            },
        ),
        migrations.CreateModel(
            name='TipoEntidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Entidade',
                'verbose_name_plural': 'Tipos de Entidade',
            },
        ),
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade')),
                ('tipo_entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoentidade', verbose_name='Tipo de Entidade')),
            ],
            options={
                'verbose_name': 'Entidade',
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('entidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.entidade', verbose_name='Entidade vinculada')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado', verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='LoteResiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_unico', models.CharField(max_length=50, unique=True, verbose_name='Identificador Único')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso (kg)')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('entidade_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.entidade', verbose_name='Entidade de Origem')),
                ('material_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.materialtipo', verbose_name='Tipo de Material')),
            ],
            options={
                'verbose_name': 'Lote de Resíduo',
                'verbose_name_plural': 'Lotes de Resíduos',
            },
        ),
        migrations.CreateModel(
            name='InspecaoQualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inspecao', models.DateTimeField(verbose_name='Data da Inspeção')),
                ('observacoes', models.TextField(verbose_name='Observações')),
                ('aprovado', models.BooleanField(verbose_name='Aprovado')),
                ('lote_residuo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.loteresiduo', verbose_name='Lote de Resíduo')),
            ],
            options={
                'verbose_name': 'Inspeção de Qualidade',
                'verbose_name_plural': 'Inspeções de Qualidade',
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_autenticidade', models.CharField(max_length=100, unique=True, verbose_name='Código de Autenticidade')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('lote_residuo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.loteresiduo', verbose_name='Lote de Resíduo')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
            },
        ),
        migrations.CreateModel(
            name='AgendamentoColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prevista', models.DateTimeField(verbose_name='Data Prevista')),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.entidade', verbose_name='Transportadora')),
                ('lote_residuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.loteresiduo', verbose_name='Lote de Resíduo')),
            ],
            options={
                'verbose_name': 'Agendamento de Coleta',
                'verbose_name_plural': 'Agendamentos de Coleta',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('usuario_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
        migrations.CreateModel(
            name='RelatorioSustentabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField(verbose_name='Período Início')),
                ('periodo_fim', models.DateField(verbose_name='Período Fim')),
                ('total_reciclado_kg', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Reciclado (kg)')),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.entidade', verbose_name='Entidade')),
            ],
            options={
                'verbose_name': 'Relatório de Sustentabilidade',
                'verbose_name_plural': 'Relatórios de Sustentabilidade',
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_evento', models.DateTimeField(verbose_name='Data do Evento')),
                ('entidade_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.entidade', verbose_name='Entidade Destino')),
                ('lote_residuo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.loteresiduo', verbose_name='Lote de Resíduo')),
                ('status_movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.statusmovimentacao', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
            },
        ),
    ]
