# Generated by Django 5.2.14 on 2026-06-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteresiduo',
            name='data_criacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Criação'),
        ),
    ]
