# Generated by Django 5.2.14 on 2026-06-01 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_loteresiduo_data_criacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loteresiduo',
            options={},
        ),
    ]
