# Generated by Django 5.2.14 on 2026-06-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_loteresiduo_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacao',
        ),
    ]
